[build]
  command = "npm run build"
  publish = "dist"

[context.production]
  environment = { NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1" }

[context.deploy-preview]
  environment = { NODE_VERSION = "16.13.2", RUBY_VERSION = "2.7.1" }

[dev]
  command = "npm run dev"
  publish = "build"
  port = 3000
  targetPort = 8080
  framework = "#custom"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' https://poetics-static.s3.eu-west-2.amazonaws.com/ https://rsms.me https://www.facebook.com https://connect.facebook.net https://api.netlify.com https://www.googletagmanager.com https://www.google-analytics.com https://www.redditstatic.com https://static.klaviyo.com; style-src 'self'  https://rsms.me 'unsafe-inline'; script-src https://poetics-static.s3.eu-west-2.amazonaws.com/ https://www.redditstatic.com https://www.facebook.com https://connect.facebook.net https://www.googletagmanager.com https://www.google-analytics.com https://static.klaviyo.com 'self' 'unsafe-eval' 'unsafe-inline'; worker-src 'self' blob:;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
